"""create tables

Revision ID: 5902e1342606
Revises: 
Create Date: 2016-09-22 15:23:21.442197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5902e1342606'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_column('sys_user', 'email_confirmed')
    op.drop_column('sys_user', 'invitation_count')
    op.drop_column('sys_user', 'access_failed_count')
    op.drop_column('sys_user', 'phone_number_confirmed')
    op.drop_column('sys_user', 'invitation_limit')
    op.drop_column('sys_user', 'lockout_enabled')
    op.drop_column('sys_user', 'security_stamp')
    op.drop_column('sys_user', 'two_factor_enabled')
    op.drop_column('sys_user', 'parent_id')
    op.drop_column('sys_user', 'invitation_code')
    op.drop_column('sys_user', 'from')
    op.drop_column('sys_user', 'merchant_id')
    op.drop_column('sys_user', 'type_id')
    op.drop_column('sys_user', 'lockout_end_date_utc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('lockout_end_date_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sys_user', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('from', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('invitation_code', sa.VARCHAR(length=18), autoincrement=False, nullable=True))
    op.add_column('sys_user', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('two_factor_enabled', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('security_stamp', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('sys_user', sa.Column('lockout_enabled', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('invitation_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('phone_number_confirmed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('access_failed_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('invitation_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sys_user', sa.Column('email_confirmed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('name', name='users_name_key')
    )
    ### end Alembic commands ###
