"""add article

Revision ID: b3b76c222121
Revises: 5902e1342606
Create Date: 2016-09-22 16:00:40.416138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b76c222121'
down_revision = '5902e1342606'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=2048), nullable=True),
    sa.Column('read_num', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('picture_tickets', sa.Text(), nullable=True),
    sa.Column('picture_number', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('check', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_article_user_id'), 'sys_article', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_article_user_id'), table_name='sys_article')
    op.drop_table('sys_article')
    ### end Alembic commands ###
